apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4000
    - protocol: TCP
      port: 4003
      targetPort: 5000
  selector:
    app: nest-server
