apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 4002
      targetPort: 3000
  selector:
    app: nest-server