apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: mysql-NodePort
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3306
    nodePort: 30001