apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-ser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest-ser
    spec:
      containers:
      - name: nest
        image: kakaru0/tavr-demo-prototype-nest:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
        ports:
        - containerPort: 4000
