apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nest-serve
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 4000
    nodePort: 30001