apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: airflow-nfs
  resources:
    requests:
      storage: 10Gi
  