apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-server
  template:
    metadata:
      labels:
        app: py-server
    spec:
      containers:
      - name: py-server
        image: kakaru0/python-server:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
        ports:
        - containerPort: 8000
